// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBj1xejQzgGc8ZAIMb4QVPmcBCIqMoA3DY',
    appId: '1:710848570046:web:5fc85172b7396e447fb4ef',
    messagingSenderId: '710848570046',
    projectId: 'qless-b4cdf',
    authDomain: 'qless-b4cdf.firebaseapp.com',
    storageBucket: 'qless-b4cdf.firebasestorage.app',
    measurementId: 'G-5BP61B1PE4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxBoVdNXHIjzgET87PAtjwsczNnzKR_Lo',
    appId: '1:710848570046:android:eb89a499b4674cba7fb4ef',
    messagingSenderId: '710848570046',
    projectId: 'qless-b4cdf',
    storageBucket: 'qless-b4cdf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoaSz4GnVCPVPWeigk-oXdFAMgb9rQrQ0',
    appId: '1:710848570046:ios:53342b753627165f7fb4ef',
    messagingSenderId: '710848570046',
    projectId: 'qless-b4cdf',
    storageBucket: 'qless-b4cdf.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoaSz4GnVCPVPWeigk-oXdFAMgb9rQrQ0',
    appId: '1:710848570046:ios:53342b753627165f7fb4ef',
    messagingSenderId: '710848570046',
    projectId: 'qless-b4cdf',
    storageBucket: 'qless-b4cdf.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBj1xejQzgGc8ZAIMb4QVPmcBCIqMoA3DY',
    appId: '1:710848570046:web:86bd7f0224d4fd2b7fb4ef',
    messagingSenderId: '710848570046',
    projectId: 'qless-b4cdf',
    authDomain: 'qless-b4cdf.firebaseapp.com',
    storageBucket: 'qless-b4cdf.firebasestorage.app',
    measurementId: 'G-VWQS5B5117',
  );
}
